image: python:3.10-bullseye

stages:
  - test

test:lint:
  stage: test
  script:
    - make init
    - make git/submodules-update         ## Requires init before target available
    - TERRAFORM_VERSION=1.3.7 make lint  ## Run Terraform linters and validation
